"""
Definition of forms.
"""

from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _
from decimal import *

#Generated by Visual studio
class BootstrapAuthenticationForm(AuthenticationForm):
    """Authentication form which uses boostrap CSS."""
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'User name'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder':'Password'}))

SEX_CHOICES = (
    ('male', 'Male'),
    ('female', 'Female')
)

EDUCATION_CHOICES = (
    ('lessThanHigh', 'Less than high school degree'),
    ('high', 'High school graduate, diploma or equivalent' ),
    ('tehnical', 'Trade, technical or vocational training'),
    ('someCollege', 'Some college credit, no degree'),
    ('bachelor', "Bachelor's degree"),
    ('master', "Masters degree"),
    ('professional', "Professional degree"),
    ('doctor', 'Doctorate degree'),
)

EMPLOYMENT_CHOICES = (
    ('wages', 'Employed for wages'),
    ('self', 'Self-employed'),
    ('unemployedLooking', 'Unemployed and looking for work'),
    ('unemployedNotLooking', 'Unemployed and not looking for work'),
    ('homemaker', 'Homemaker'),
    ('student', 'Student'),
    ('military', 'Military'),
    ('retired', 'Retired'),
    ('unable', 'Unable to work'),
)

RESIDENCE_CHOICES = (
    ('rural', 'Rural area'),
    ('suburban', 'Suburban area'),
    ('urban', 'Urban area')
)

class UserInfo(forms.Form):
    sex = forms.ChoiceField(required=True,
                            choices=SEX_CHOICES,
    )
    age = forms.IntegerField(required=True, 
                             max_value=120, 
                             min_value=1,
    )
    education = forms.ChoiceField(required=True,
                                  choices=EDUCATION_CHOICES,
    )
    employment = forms.ChoiceField(required=True,
                                  choices=EMPLOYMENT_CHOICES,
    )
    residence = forms.ChoiceField(required=True,
                                  choices=RESIDENCE_CHOICES,
    )
    threshold = forms.DecimalField(min_value=Decimal(0),
                                   max_value=Decimal(100),
                                   decimal_places=4,
                                   required=False,
    )