"""
Definition of views.
"""

from django.shortcuts import render
from django.http import HttpRequest
from django.template import RequestContext
from datetime import datetime
from app.forms import UserInfo 

# Generated by Viusal studio
def home(request):
    """Renders the home page."""
    assert isinstance(request, HttpRequest)
    return render(
        request,
        'app/index.html',
        context_instance = RequestContext(request,
        {
            'title':'Home Page',
            'year':datetime.now().year,
        })
    )

def contact(request):
    """Renders the contact page."""
    assert isinstance(request, HttpRequest)
    return render(
        request,
        'app/contact.html',
        context_instance = RequestContext(request,
        {
            'title':'Contact',
            'message':'Your contact page.',
            'year':datetime.now().year,
        })
    )

def about(request):
    """Renders the about page."""
    assert isinstance(request, HttpRequest)
    return render(
        request,
        'app/about.html',
        context_instance = RequestContext(request,
        {
            'title':'About',
            'message':'Your application description page.',
            'year':datetime.now().year,
        })
    )


#Our view
#w3b form try
def w3b(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        # this worked form = NameForm(request.POST)
        form = UserInfo(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            sex = form.cleaned_data.get('sex')
            age = form.cleaned_data.get('age')
            employment = form.cleaned_data.get('employment')
            education = form.cleaned_data.get('education')
            residence = form.cleaned_data.get('residence')
            threshold = form.cleaned_data.get('threshold')

            return render(request, 'app/w3b.html', {'form':form,
                                                    'prob1':sex,
                                                    'prob2':age,
                                                    'prob3':employment,
                                                    'prob4':education,
                                                    'prob5':residence,
                                                    'prob6':threshold,
                                                    'prob7':90,
                                                    'prob8':90,})

    # if a GET (or any other method) we'll create a blank form
    else:
        form = UserInfo()

    return render(request, 'app/w3b.html', {'form':form,
                                            'prob1':20,
                                            'prob2':30,
                                            'prob3':40,
                                            'prob4':30,
                                            'prob5':40,
                                            'prob6':60,
                                            'prob7':90,
                                            'prob8':90,
})